// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2x6Bx48bEPnTZzVsotPWszg9UAEd7Vo',
    appId: '1:642657997208:web:3e773e5d77b1307bd59bed',
    messagingSenderId: '642657997208',
    projectId: 'beograd-plus-b333c',
    authDomain: 'beograd-plus-b333c.firebaseapp.com',
    storageBucket: 'beograd-plus-b333c.appspot.com',
    measurementId: 'G-EHFSFM653G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtTFmrT7zp6jdovVWC--nzfeqnYkh5SE',
    appId: '1:642657997208:android:0b913f19b2cf6dc0d59bed',
    messagingSenderId: '642657997208',
    projectId: 'beograd-plus-b333c',
    storageBucket: 'beograd-plus-b333c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYfVpovhKT4IQbCAT8t6Z0ZVpVVMLtBNQ',
    appId: '1:642657997208:ios:d47c47082a413859d59bed',
    messagingSenderId: '642657997208',
    projectId: 'beograd-plus-b333c',
    storageBucket: 'beograd-plus-b333c.appspot.com',
    iosBundleId: 'rs.beogradplus.travelApp',
  );
}
